name: Auto Assign to SDK Project

on:
  issues:
    types: opened

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to SDK project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        project: 'https://github.com/orgs/decentraland/projects/20'
